#!/bin/bash
# ============================================================
# Production Deployment Configuration (4 Machines)
#   1 × TiKV  (single node, single replica)
#   3 × Ceph   (MON+MGR+OSD+RGW, EC 4+2)
#   Client: shared on TiKV or Ceph machines (see README)
#
# Edit this file with your actual server IPs before running.
# ============================================================

# --- TiKV: Single Node (PD + TiKV co-located) ---
# This machine serves JuiceFS metadata.
# Running single-replica mode (no Raft group).
# Minimum: 4 CPU, 8GB RAM, 50GB+ fast SSD
TIKV_SERVER="192.168.11.12"   # tikv-node (this machine)
TIKV_DATA_DEVICE="/dev/sdb"   # dedicated disk for TiKV/PD data (/data mount)

TIKV_DATA_DIR="/data/tikv"
PD_DATA_DIR="/data/pd"

TIKV_VERSION="v7.1.5"
PD_VERSION="v7.1.5"

# --- Ceph Cluster (3 servers, MON+MGR+OSD+RGW) ---
# These servers provide object storage (S3) for JuiceFS data.
# Each server: MON + MGR + OSDs.  RGW on first 2 servers.
# Minimum: 4 CPU, 8GB RAM, dedicated OSD disks per server
CEPH_SERVERS=(
  "192.168.11.11"   # ceph-node1
  "192.168.11.13"   # ceph-node2
  "192.168.11.14"   # ceph-node3
)

# OSD block devices on each Ceph server (unformatted, unmounted, one disk
# per server).  Each disk will be split into 2 equal partitions by
# deploy-ceph.sh → 3 servers × 2 partitions = 6 OSDs for EC 4+2.
# Index matches CEPH_SERVERS.
#   ceph-node1: sdb=953G (reinstalled 2026-06; system now on sda, sdb freed)
#   ceph-node2: sdb=953G
#   ceph-node3: sdb=953G
# Capacity: all OSD disks ~953G → EC 4+2 usable ~1.9T (efficiency ~67%)
CEPH_OSD_DEVICES=( "/dev/sdb" "/dev/sdb" "/dev/sdb" )

# EC pool configuration
# k=4 data chunks + m=2 parity = 6 chunks total
# Each node creates 2 LVs from its data disk → 3 × 2 = 6 OSDs
# failure-domain=osd: 2 OSD failures tolerated
CEPH_EC_K=4
CEPH_EC_M=2
CEPH_FAILURE_DOMAIN="osd"

# --- JuiceFS Client ---
# Which machine runs JuiceFS mount (FUSE process).
# Per our strategy:
#   Data-heavy tests  → ${TIKV_SERVER}
#   Metadata-heavy tests → one of CEPH_SERVERS
# Set this before each test run; scripts use PD_ENDPOINTS + RGW_ENDPOINT.
JUICEFS_CLIENT="${TIKV_SERVER}"

JUICEFS_FS_NAME="juicefs-prod"
JUICEFS_MOUNT_POINT="/mnt/juicefs"

# --- SSH Configuration ---
# All servers use user 'turboai'.  Run setup-ssh-keys.sh first to
# generate a key pair and copy the public key to every target server.
# Commands that need root (package install, cephadm, systemd, etc.)
# are run via sudo.  cephadm inter-node communication still requires
# root SSH — deploy-ceph.sh handles this by distributing ceph.pub.
SSH_USER="turboai"
SSH_KEY="${HOME}/.ssh/id_ed25519"       # generated by setup-ssh-keys.sh
SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=10"

# --- Network ---
# Single PD endpoint (single-node, no Raft group)
PD_ENDPOINTS="${TIKV_SERVER}:2379"

# --- Ceph RGW endpoint (for JuiceFS S3 access) ---
# With a single RGW, point JuiceFS directly at it (e.g. CEPH_SERVERS[0]:8000).
# With multiple RGWs, deploy an LB (deploy-lb.sh) and set RGW_ENDPOINT to
# the LB address so traffic is spread across all RGW backends — otherwise
# JuiceFS only ever talks to one RGW.
# NOTE: defined after the LB block below so ${LB_HOST}/${LB_PORT} are set.

# --- RGW load balancer (HAProxy) ---
# Only meaningful when there is more than one RGW.  deploy-lb.sh installs
# HAProxy on LB_HOST and balances LB_PORT across RGW_BACKENDS (round-robin
# with health checks).  After running it, set RGW_ENDPOINT above to
# "http://${LB_HOST}:${LB_PORT}".
#
# LB_HOST: where HAProxy runs.  Default = TiKV node (gigabit, not an RGW
# host, so the LB itself isn't competing with an RGW for the same NIC).
LB_HOST="${TIKV_SERVER}"
LB_PORT="8080"
# RGW backends the LB fans out to (ip:port).  Must match the RGW placement
# in deploy-ceph.sh (currently ceph-node1 + ceph-node3, both :8000).
RGW_BACKENDS=(
  "${CEPH_SERVERS[0]}:8000"   # ceph-node1
  "${CEPH_SERVERS[2]}:8000"   # ceph-node3
)

# JuiceFS S3 endpoint: point at the LB so both RGWs get traffic.
# (For single-RGW setups, set this to "http://${CEPH_SERVERS[0]}:8000".)
RGW_ENDPOINT="http://${LB_HOST}:${LB_PORT}"

# --- Binary download mirror ---
TIKV_MIRROR="https://tiup-mirrors.pingcap.com"
