global:
  user: "root"
  ssh_port: 22
  deploy_dir: "/opt/tikv-deploy"
  data_dir: "/data"

pd_servers:
  - host: 192.168.11.12

tikv_servers:
  - host: 192.168.11.12
    data_dir: "/data/tikv"

monitoring_servers: []
grafana_servers: []
alertmanager_servers: []
