apiVersion: 1

deleteDatasources: []

datasources:
  - name: JuiceFS-Prometheus
    uid: juicefs-prometheus
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 10s
